name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Astro Check
        run: npx astro check

      - name: Build site
        run: npm run build

      - name: Check for broken links
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411
        with:
          args: --verbose --no-progress --root-dir ./dist --exclude '^https://dev\.jamovi\.org' './dist/**/*.html'
          fail: true
